# app/services/orchestration/domain/ports.py
"""
Orchestration Domain Ports
===========================
Protocols for orchestration dependencies.
"""

from __future__ import annotations

from typing import Protocol

from app.services.orchestration.domain.models import (
    AutoScalingConfig,
    Node,
    Pod,
    RaftState,
    SelfHealingEvent,
)


class PodRepository(Protocol):
    """Port for pod storage"""
    def save(self, pod: Pod) -> None: ...
    def get(self, pod_id: str) -> Pod | None: ...
    def get_all(self) -> list[Pod]: ...
    def get_by_node(self, node_id: str) -> list[Pod]: ...
    def delete(self, pod_id: str) -> None: ...


class NodeRepository(Protocol):
    """Port for node storage"""
    def save(self, node: Node) -> None: ...
    def get(self, node_id: str) -> Node | None: ...
    def get_all(self) -> list[Node]: ...
    def update(self, node: Node) -> None: ...


class HealingEventRepository(Protocol):
    """Port for healing event storage"""
    def save(self, event: SelfHealingEvent) -> None: ...
    def get_recent(self, limit: int) -> list[SelfHealingEvent]: ...


class ConsensusEngine(Protocol):
    """Port for consensus protocol"""
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def append_log_entry(self, entry: dict) -> bool: ...
    def get_state(self) -> RaftState: ...
    def is_leader(self) -> bool: ...


class ScalingEngine(Protocol):
    """Port for auto-scaling"""
    def configure(self, config: AutoScalingConfig) -> None: ...
    def check_scaling_needed(self, deployment: str) -> tuple[bool, int]: ...
    def scale_deployment(self, deployment: str, replicas: int) -> bool: ...  # noqa: unused variable
