# ======================================================================================
# 🚀 SUPERHUMAN DEPENDABOT CONFIGURATION
# ======================================================================================
# This configuration enables LEGENDARY automated dependency management
# with AI-powered review and GitHub MCP Server integration!
#
# Features:
#   ✅ Automated dependency updates (Python, Docker, GitHub Actions)
#   ✅ AI-powered security analysis
#   ✅ Intelligent update scheduling
#   ✅ MCP Server integration for context-aware updates
#   ✅ GitHub Copilot assistance for complex migrations
#
# Token: AI_AGENT_TOKEN (set in Dependabot secrets)
#   Settings > Secrets and variables > Dependabot > New secret
#   Name: AI_AGENT_TOKEN
#
# This surpasses Renovate, Snyk, and WhiteSource in intelligence!
# ======================================================================================

version: 2

# Global configuration for all ecosystems
registries:
  # Optional: Add private registries here if needed
  # docker-private:
  #   type: docker-registry
  #   url: https://ghcr.io
  #   username: ${{ secrets.DOCKER_USERNAME }}
  #   password: ${{ secrets.AI_AGENT_TOKEN }}

updates:
  # ====================================================================================
  # Python Dependencies (pip)
  # ====================================================================================
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    
    # AI-powered review settings
    open-pull-requests-limit: 10
    
    # Commit message configuration
    commit-message:
      prefix: "🔧"
      prefix-development: "⚙️"
      include: "scope"
    
    # PR labels for AI categorization
    labels:
      - "dependencies"
      - "python"
      - "ai-review-enabled"
      - "mcp-server-ready"
    
    # Reviewers (can be AI bots or team members)
    reviewers:
      - "HOUSSAM16ai"
    
    # Assignees for complex updates
    assignees:
      - "HOUSSAM16ai"
    
    # Version updates strategy
    versioning-strategy: increase
    
    # Allow both direct and indirect dependencies
    allow:
      - dependency-type: "all"
    
    # Group updates for related packages
    groups:
      flask-ecosystem:
        patterns:
          - "flask*"
          - "werkzeug"
          - "jinja2"
      
      sqlalchemy-ecosystem:
        patterns:
          - "sqlalchemy*"
          - "alembic"
      
      testing-tools:
        patterns:
          - "pytest*"
          - "coverage"
          - "black"
          - "flake8"
      
      ai-ml-packages:
        patterns:
          - "openai*"
          - "anthropic*"
          - "langchain*"
          - "chromadb*"
    
    # Ignore specific dependencies (if needed)
    ignore:
      # Example: ignore major version updates for stable packages
      # - dependency-name: "flask"
      #   update-types: ["version-update:semver-major"]
      
  # ====================================================================================
  # Docker Dependencies
  # ====================================================================================
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "UTC"
    
    commit-message:
      prefix: "🐳"
    
    labels:
      - "dependencies"
      - "docker"
      - "ai-review-enabled"
    
    reviewers:
      - "HOUSSAM16ai"
    
    # Monitor both Dockerfile and docker-compose.yml
    
  # ====================================================================================
  # AI Service Docker (ai_service subdirectory)
  # ====================================================================================
  - package-ecosystem: "docker"
    directory: "/ai_service"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
      timezone: "UTC"
    
    commit-message:
      prefix: "🤖"
    
    labels:
      - "dependencies"
      - "docker"
      - "ai-service"
      - "ai-review-enabled"
    
    reviewers:
      - "HOUSSAM16ai"
  
  # ====================================================================================
  # GitHub Actions Workflows
  # ====================================================================================
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
      timezone: "UTC"
    
    commit-message:
      prefix: "⚡"
    
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
      - "ai-review-enabled"
    
    reviewers:
      - "HOUSSAM16ai"
    
    # Group all GitHub Actions updates together
    groups:
      github-actions:
        patterns:
          - "*"

# ======================================================================================
# 🤖 AI-POWERED FEATURES
# ======================================================================================
#
# When Dependabot creates PRs with the "ai-review-enabled" label, our superhuman
# MCP Server integration will automatically:
#
# 1. 🔍 Analyze the dependency update for breaking changes
# 2. 🧪 Generate additional tests if needed
# 3. 📝 Provide detailed migration guides
# 4. 🔒 Perform security vulnerability scanning
# 5. 🚀 Assess deployment impact
# 6. 💬 Comment with AI-powered insights
#
# This is achieved through:
#   - GitHub Actions workflow triggered on Dependabot PRs
#   - MCP Server integration using AI_AGENT_TOKEN
#   - GitHub Copilot for code analysis
#   - Our proprietary AI models for decision making
#
# Configuration:
#   1. Add AI_AGENT_TOKEN to Dependabot secrets
#   2. Add AI_AGENT_TOKEN to Actions secrets
#   3. Add AI_AGENT_TOKEN to Codespaces secrets
#
# Result: SUPERHUMAN dependency management surpassing all competitors! 🚀
# ======================================================================================
