# .gitpod.yml - v6.0 (Silent Helper)
# This project is now 100% controlled by the universal .devcontainer.json standard.
# This file is intentionally left almost empty to prevent any conflicts.
# Its only job is to provide a better user experience by opening ports.

ports:
  - port: 5000
    onOpen: open-browser
    name: Flask Web App
  - port: 8000
    onOpen: open-preview
    name: FastAPI AI Core

