# .gitpod.yml - v7.0 (The Smart Helper)
# This file now has ONE critical task: ensure the .env file exists before
# the Dev Container protocol begins. This solves the startup failure.

tasks:
  - name: Prepare Environment
    before: |
      echo ">>> [Gitpod] Ensuring .env file exists..."
      if [ ! -f .env ]; then
        cp .env.example .env
        echo ">>> [Gitpod] .env file created from template."
      else
        echo ">>> [Gitpod] .env file already exists."
      fi

ports:
  - port: 5000
    onOpen: open-browser
    name: Flask Web App
  - port: 8000
    onOpen: open-preview
    name: FastAPI AI Core

