image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup and Launch
    init: |
      echo "Installing Python packages..."
      pip install -r requirements.txt
      echo "Starting services via docker-compose..."
      docker-compose up -d
      echo "Waiting for services to be ready..."
      sleep 20
      echo "Creating database tables..."
      # This is the new, more robust way to provide the password
      export PGPASSWORD='password'
      psql -h localhost -U user -d mydb -f schema.sql
    command: |
      echo "Application is running. Use 'docker-compose logs -f web' to see logs."

ports:
  - port: 5000
    onOpen: open-browser
    