# setup_environment.py
import argparse
import os
import re
import subprocess

# Superhuman Edition: A dynamic, multi-mode environment setup script.
# It can bootstrap from the system environment (for initial create)
# AND perform a live sync from GitHub secrets (for attach/reconnect).

def get_var_name_from_line(line):
    line = line.strip()
    if not line or line.startswith('#'):
        return None
    match = re.match(r'^([a-zA-Z_][a-zA-Z0-9_]*)', line)
    return match.group(1) if match else None

def write_env_file(env_vars, mode):
    if not os.path.exists(".env"):
        print("📄 '.env' file not found. Creating it...")
        header = f"# This file was auto-generated by setup_environment.py in '{mode}' mode\n"
        with open(".env", "w") as f:
            f.write(header)
            f.writelines(env_vars)
        print("✅ Successfully created '.env' file.")
    else:
        print("🔄 '.env' file exists. Merging/updating secrets...")
        # A simple merge: append new keys, update existing ones
        existing_vars = {}
        with open(".env") as f:
            for line in f:
                if not line.strip().startswith('#'):
                    key, _, _ = line.partition('=')
                    existing_vars[key.strip()] = line

        new_vars_dict = {key: line for key, line in (line.partition('=')[::2] for line in env_vars)}

        # Update existing vars or append new ones
        for key, line in new_vars_dict.items():
            existing_vars[key] = line

        with open(".env", "w") as f:
            f.writelines(existing_vars.values())
        print("✅ '.env' file updated.")

def from_system_env():
    print("⚙️  Mode: System Environment Bootstrap")
    example_file = ".env.example"
    if not os.path.exists(example_file):
        print(f"❌ Error: '{example_file}' not found.")
        return

    print(f"📄 Reading variable names from '{example_file}'...")
    env_lines = []
    with open(example_file) as f:
        for line in f:
            var_name = get_var_name_from_line(line)
            if var_name:
                value = os.getenv(var_name)
                if value:
                    print(f"  ✅ Found '{var_name}' in system environment.")
                    env_lines.append(f'{var_name}="{value}"\n')

    if env_lines:
        write_env_file(env_lines, "system")
    else:
        print("- No relevant variables found in system environment.")

def from_github_live():
    print("🚀 Mode: Live Sync from GitHub Secrets")
    try:
        # Check if gh is installed and authenticated
        subprocess.run(["gh", "auth", "status"], check=True, capture_output=True)
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("❌ Error: GitHub CLI ('gh') is not installed or not authenticated.")
        print("   Cannot perform a live sync. Please run 'gh auth login' in the terminal.")
        return

    print("📡 Fetching secrets from GitHub repository...")
    try:
        result = subprocess.run(
            ["gh", "secret", "list", "--json", "name,value"],
            capture_output=True, text=True, check=True
        )
        secrets = json.loads(result.stdout)
    except (subprocess.CalledProcessError, json.JSONDecodeError) as e:
        print(f"❌ Error fetching secrets: {e}")
        return

    if not secrets:
        print("- No secrets found in the GitHub repository.")
        return

    env_lines = [f'{secret["name"]}="{secret["value"]}"\n' for secret in secrets]
    print(f"✅ Found {len(secrets)} secrets.")

    write_env_file(env_lines, "live-sync")

def main():
    parser = argparse.ArgumentParser(description="Superhuman environment setup script.")
    parser.add_argument(
        '--live-sync',
        action='store_true',
        help="Perform a live sync from GitHub secrets instead of using system env."
    )
    args = parser.parse_args()

    if args.live_sync:
        from_github_live()
    else:
        from_system_env()

    print("\n🎉 Environment setup complete.")

if __name__ == "__main__":
    import json  # Import json only when needed
    main()
