apiVersion: v1
kind: Namespace
metadata:
  name: ai-services
  labels:
    istio-injection: enabled
    name: ai-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-service
  namespace: ai-services
  labels:
    app: router-service
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: router-service
      version: v1
  template:
    metadata:
      labels:
        app: router-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: router-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532
      containers:
        - name: router-service
          image: ghcr.io/houssam16ai/my_ai_project/router-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector.observability.svc.cluster.local:4317"
            - name: REDIS_URL
              value: "redis://redis-master.infrastructure.svc.cluster.local:6379"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: router-service
  namespace: ai-services
spec:
  type: ClusterIP
  selector:
    app: router-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: router-service
  namespace: ai-services
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: router-service-hpa
  namespace: ai-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: router-service
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
