"""Complete Phase 3: Add rating and history management

Revision ID: 8059ddf70ed8
Revises: e7093d7dd84a
Create Date: 2025-08-21 12:12:58.920928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8059ddf70ed8'
down_revision = 'e7093d7dd84a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_rating'), ['rating'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_rating'))

    # ### end Alembic commands ###
