from typing import Protocol, List, Dict, Optional, Deque
from .models import (
    TelemetryData,
    AnomalyDetection,
    LoadForecast,
    HealingDecision,
    CapacityPlan,
    MetricType
)

class TelemetryRepository(Protocol):
    def add(self, data: TelemetryData) -> None: ...
    def get_by_service(self, service_name: str, metric_type: MetricType) -> List[TelemetryData]: ...
    def get_all(self) -> Dict[str, Deque[TelemetryData]]: ...

class AnomalyRepository(Protocol):
    def add(self, anomaly: AnomalyDetection) -> None: ...
    def get(self, anomaly_id: str) -> Optional[AnomalyDetection]: ...
    def get_all(self) -> Dict[str, AnomalyDetection]: ...
    def update(self, anomaly: AnomalyDetection) -> None: ...

class HealingDecisionRepository(Protocol):
    def add(self, decision: HealingDecision) -> None: ...
    def get_all(self) -> Dict[str, HealingDecision]: ...

class ForecastRepository(Protocol):
    def add(self, service_name: str, forecast: LoadForecast) -> None: ...
    def get(self, service_name: str) -> Deque[LoadForecast]: ...
    def get_all(self) -> Dict[str, Deque[LoadForecast]]: ...

class CapacityPlanRepository(Protocol):
    def add(self, service_name: str, plan: CapacityPlan) -> None: ...
    def get(self, service_name: str) -> Optional[CapacityPlan]: ...
    def get_all(self) -> Dict[str, CapacityPlan]: ...
