apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-services
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/HOUSSAM16ai/my_ai_project
    targetRevision: HEAD
    path: apps
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-services
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/HOUSSAM16ai/my_ai_project
    targetRevision: HEAD
    path: infra/k8s
  
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai-platform
  namespace: argocd
spec:
  description: AI Microservices Platform
  
  sourceRepos:
    - https://github.com/HOUSSAM16ai/my_ai_project
  
  destinations:
    - namespace: 'ai-services'
      server: https://kubernetes.default.svc
    - namespace: 'infrastructure'
      server: https://kubernetes.default.svc
    - namespace: 'observability'
      server: https://kubernetes.default.svc
    - namespace: 'ai-models'
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  
  roles:
    - name: developer
      description: Developers
      policies:
        - p, proj:ai-platform:developer, applications, get, ai-platform/*, allow
        - p, proj:ai-platform:developer, applications, sync, ai-platform/*, allow
      groups:
        - developers
    
    - name: admin
      description: Administrators
      policies:
        - p, proj:ai-platform:admin, applications, *, ai-platform/*, allow
      groups:
        - admins
