from collections import deque
from typing import Protocol

from .models import (
    AnomalyDetection,
    CapacityPlan,
    HealingDecision,
    LoadForecast,
    MetricType,
    TelemetryData,
)

class TelemetryRepository(Protocol):
    def add(self, data: TelemetryData) -> None: ...
    def get_by_service(self, service_name: str, metric_type: MetricType) -> list[TelemetryData]: ...
    def get_all(self) -> dict[str, deque[TelemetryData]]: ...

class AnomalyRepository(Protocol):
    def add(self, anomaly: AnomalyDetection) -> None: ...
    def get(self, anomaly_id: str) -> AnomalyDetection | None: ...
    def get_all(self) -> dict[str, AnomalyDetection]: ...
    def update(self, anomaly: AnomalyDetection) -> None: ...

class HealingDecisionRepository(Protocol):
    def add(self, decision: HealingDecision) -> None: ...
    def get_all(self) -> dict[str, HealingDecision]: ...

class ForecastRepository(Protocol):
    def add(self, service_name: str, forecast: LoadForecast) -> None: ...
    def get(self, service_name: str) -> deque[LoadForecast]: ...
    def get_all(self) -> dict[str, deque[LoadForecast]]: ...

class CapacityPlanRepository(Protocol):
    def add(self, service_name: str, plan: CapacityPlan) -> None: ...
    def get(self, service_name: str) -> CapacityPlan | None: ...
    def get_all(self) -> dict[str, CapacityPlan]: ...
